### ISSUE TITLE
Heads-up about the `Key` type

### ISSUE THREAD

**Issue by patrick-kidger** [google-deepmind/synjax#1]
Heyhey! I'm just starting to poke through this. Congraulations on the new release!

I can see you've got a `Key` datatype here:
https://github.com/deepmind/synjax/blob/adb3c05de8b1ae252940bda947ddf7332a09b1f2/synjax/_src/typing.py#L22

Heads-up that this will stop working once JAX lands custom PRNGs (quite soon now), as these will then become arrays with a custom "key" dtype. I'd recommend `jaxtyping.PRNGKeyArray` for something compatible with both sides of that change. :)

**Comment by stanojevic** [comment]
Good point. I should change that before it starts causing problems with the new release.

**Comment by stanojevic** [comment]
Addressed with commit 1014493b5f36ad0222ad9abc1ff4737dd7db1013.
